baseURL = "https://camuthig.github.io"
languageCode = "en-us"
title = "Chris Muthig"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Chris Muthig"
    description = "A software developer with a passion for helping others"
    githubUsername = "#"
    accent = "teal"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "darcula"
    highlightLanguages = ["go", "kotlin", "scala"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

# [[menu.main]]
#     url = "/projects/"
#     name = "Projects"
#     weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/


[[menu.icon]]
    url = "https://github.com/camuthig/"
    name = "github"
    weight = 1


[[menu.icon]]
    url = "https://www.linkedin.com/in/camuthig/"
    name = "linkedin"
    weight = 2
